### ISSUE TITLE
Attitude estimate computed on controller instable/unreliable

### ISSUE THREAD

**Issue by skohlbr** [rosflight/rosflight_firmware#289] opened 2018-04-05 21:34 UTC
16.04/AMD64/Kinetic
master branch
Naze32 FC (ordered off ebay, so possibly copy)

I'm observing that the attitude estimate provided by the rosflight FW is pretty unreliable. After resetting via the available service, it works fine for some time, but often starts spinning around some axis after a few minutes (even if the board just sits still on the table).
If I feed the raw accelerometer and gyro data to either [imu_filter_madgwick](http://wiki.ros.org/imu_filter_madgwick) or [imu_complementary_filter](http://wiki.ros.org/imu_complementary_filter) instead, the attitude estimates coming out of those look fine and stay stable. Given this fact, it seems the sensor data should not be the culprit.
As my main use for the FC is as a IMU for an autonomous vehicle, I can just use the previously described setup, but it would still be nicer to get already good estimates from the firmware.

**Comment by superjax** [comment] 2018-04-05 22:31
That's pretty concerning...  Thanks for letting us know! 

Do you happen to have a rosbag of this happening?  I have seen this in the past, but I thought that I had fixed it (it was too aggressive a gain on `FILTER_KP` and `FILTER_KI`.)  I bet I still have it pretty close to the margin, because otherwise I feel like the estimator lags... haha!  Probably not too safe.

Thanks!

**Comment by skohlbr** [comment] 2018-04-09 11:47
I'll be able to get a bag file at some point, but might take a while due to other commitments.

**Comment by superjax** [comment] 2018-05-15 05:52
I've just been able to reproduce this behavior.  Thanks, definitely my bad - I've dialed down the `FILTER_KI` parameter to `0.01` and that seems to have fixed it.  I'll try running it overnight a few nights on a couple of chips to confirm that fixes it.

**Comment by korken89** [comment] 2018-09-04 06:47
Hi, I am seeing the same issue @superjax , also on a NAZE32 (AfroFlight).

By simply hovering, after a while the estimation starts to drift away until it has a bias of about (+/-) 0.2 - 0.3 radians or roll and pitch.
Lowering the KI term of the filter does not help, it only makes the issues appear slower.
While after landing the estimator converges again to the correct estimation.

I am running this inside out motion capturing arena, so I can provide any logs that you'd like.

BR Emil

**Comment by superjax** [comment] 2018-09-04 13:14
Thanks, that's really troubling.

Let me make sure I understand - You're observing a bias when flying, but not when stationary?  

If you could collect a log, that would be awesome, try to get as much imu data as possible.

**Comment by korken89** [comment] 2018-09-04 13:36
Hi, I have been testing all day and it seems to be a vibration issue.

I had a cable that was touching the clean frame (making the vibration dampening moot) which caused the issue.
This however seems a bit strange, if I understand correctly the internal IMU rate is 1000 Hz which should be far higher than any vibration of the system (plus internal IMU filtering).  And by averaging the accelerometer values should still provide a good reference.

Do you have any idea where this might come from? 

Also, I can again put the cable back and create logs if you want. Could be good to analyze the problem a bit further :)

**Comment by superjax** [comment] 2018-09-04 13:49
Yeah, we should be able to handle a disturbance like that.  I really like the notch filtering idea.  This might be a good dataset to use to develop it.

**Comment by korken89** [comment] 2018-09-04 13:56
Hmm, it could be, and I will make a dataset to test on which exhibits the problem.
I was thinking the same about the notch filter, though we could sadly never run it on the NAZE32 based boards but the new port to F4 based boards should solve that issue!

**Comment by korken89** [comment] 2018-09-04 14:29
I tried to get it to happen again and was successful, though not at extreme as before, but it shows the effect.
I have created a rosbag here https://drive.google.com/open?id=1acsgVGwNRCfrIj9HF0cErhoZFMuiIZxl with:
* IMU at 1000 Hz
* Motion capture at 100 Hz
* All other rosflight topics

I started from motors off and it continues until I have landed with motors off again, plus until the estimator has converged back and eliminated the bias again.

The issue is happening here with approx. 0.12 radians in roll and 0.09 in pitch.
The entire experiment I was hovering except once where I returned the roll and pitch stick to resting position to see how much offset there was.

If you have any questions I'm here to help!

**Comment by superjax** [comment] 2018-09-04 16:47
Awesome.  Thanks so much.  I'll hopefully get some time to look at this tonight.

In your testing, did you notice if the bias error always went the same way?

**Comment by korken89** [comment] 2018-09-04 16:51
Thanks! I'm air interested as the estimator you are using is theoretically solid, or perhaps there is some other effect at play.

As far as I tested they went the same way, though not sure if it were the same way in the first trial as I sadly didn't log that.

**Comment by superjax** [comment] 2018-09-13 22:31
Ultimately, I believe reason that the filter isn't working very well is that not very many of the IMU measurements are making it into the filter.  (check out lines [156-157 of `estimator.cpp`](https://github.com/rosflight/firmware/blob/master/src/estimator.cpp#L156) The noise on accel is so high that only 6% of the accel measurements are fused.
 
Check out the IMU data on that log

![image](https://user-images.githubusercontent.com/7344014/45518824-08672e00-b770-11e8-975c-aeb804624b76.png)

"filtered" corresponds to the LPF in the firmware. This is with an LPF of 0.5.

However, there is another thing really weird with this log - I'm seeing this really weird flipping between -9.8 and 9.8 on the z axis.  It appears to continue throughout the flight where the acceleration vector is randomly changing signs.  I haven't been able to see anything like that on my hardware.  I bumped the LPF up to 0.999 and got this:

![image](https://user-images.githubusercontent.com/7344014/45519467-685ed400-b772-11e8-98f0-14cdbc8d462d.png)

I wouldn't normally expect IMU data on the z-axis to go to zero.

Could you check and see if your IMU data looks right?  I'll keep investigating on my end to see if I can observe this in my hardware.

**Comment by korken89** [comment] 2018-09-14 07:57
Thank you for the initial analysis! I checked the data and I was  running my node to convert everything into NWU frame, `/pixyrf/imu` is in the NWU frame, while `/pixyrf/rosflight/imu` is the "raw" rosflight IMU.
Sorry for the confusion!

On the note of high noise, I have a possible suggestion.
I took a look at the estimator again and noticed the bounds you are using to reject measurements, and I was thinking that maybe a soft-limit is a better choice for noisy systems?

Like full gains for the 0.9-1.1g but exponential tails rather than full off? Or have the gains be something similar to a Gaussian full gains at 1g and then dropping off.
Something that is computationally tractable but also with desired roll-off properties.

Not 100% sure what would be a good weighting strategy though. Have you tested different ones?

**Comment by korken89** [comment] 2018-09-14 12:16
Perhaps something like this `W = 1 / ( 1 + 10000 * (x - 9.8)^4 )`

![image](https://user-images.githubusercontent.com/913109/45549597-a28aad00-b828-11e8-8eae-b4580bcaed20.png)

**Comment by superjax** [comment] 2018-09-25 20:13
Haha! oops.  Yeah, my bad.  I filtered the IMU messages in my rosbag parser and things look a lot better now.

I did a little bit of tuning
```
ACC_LPF_ALPHA: 0.9
FILTER_KI: 0.01
FILTER_KP: 0.5
```
and got this plot with the hard cutoff (before)
![image](https://user-images.githubusercontent.com/7344014/46039396-d5575f80-c0ca-11e8-9e05-9514cc1b0417.png)

I then implemented your above change and got this:
![image](https://user-images.githubusercontent.com/7344014/46039471-10599300-c0cb-11e8-92dc-b9b03dee1d3f.png)

I like the `y` estimates a lot better on this second plot.

Anyway, we now have our motion capture system up and going here, so I might spend some more time dinking around with this.  I like the new weighting scheme.

In case you're at all interested, everything I'm using to post-process this is on the `fixing_289_unstable_att` branch.  I'm running the `rosbag_parser` function built in the `test` folder 

``` bash
cd test
mkdir build
cd build
cmake ..
make
./rosbag_parser -p /home/superjax/korken_params.yaml -f ~/Downloads/rosflight_bias_in_estimator_with_ground_truth.bag -imu /pixyrf/rosflight/imu
```

then I plot the results with 
``` bash
cd scripts
python plot_post-process.py
```

**Comment by korken89** [comment] 2018-10-07 19:49
Awesome that you gave it a test!
I have been abit swamped at our lab for now, but it seems to indeed be helping.
I designed this cutoff gain to be close to what was already implemented, testing to make it not have quite as aggressive falloff would also be interesting.

**Comment by mohradza** [comment] 2019-02-20 20:40
Hello!

I think I am having similar problems regarding attitude estimates drifting, and I was hoping to get some help with finding a solution.  I am on the master branch of the firmware, and I am using a NAZE32 Rev6 board.

I have been experiencing significant estimated attitude drift during flights. Here are some plots from a flight were I was doing position control using feedback using vicon position estimates in roscopter. You can see that the attitude is continuously drifting, so much that the controller eventually cannot compensate for the error and the vehicle drifts away from its commanded position (-2.6, 0, -1). 

![flight_drift](https://user-images.githubusercontent.com/22601768/53122334-97dcee00-3513-11e9-9119-6d70dd0bb858.jpg)

What looked most concerning to me was the accelerometer measurements, which are super noisy. I decided to remount the naze board with better vibration dampening foam. While this did reduce the magnitude of the noise, I was still experiencing pretty significant attitude drift over the course of about 10 seconds of the motors spinning up. (see the following figure)

![ground_test](https://user-images.githubusercontent.com/22601768/53122665-60227600-3514-11e9-98ae-8ea10dcf1a80.jpg)

I tried changing the filter parameters mentioned above (ACC_LPF_ALPHA from .5 to .9, and FILTER_KI from .05 to .01), but I did not get results that looked very good to me:

![filter_update](https://user-images.githubusercontent.com/22601768/53122873-f9518c80-3514-11e9-8881-fa0ecadccc3e.jpg)


If anyone has any ideas of how I can fix this situation, please let me know! I can provide the rosbags if anyone wants them.

Thanks

**Comment by bsutherland333** [comment] 2023-10-04 20:38
I'm not sure if this is still an issue, but this may be useful when we revisit the onboard estimator so I'll leave it open.

**Comment by bsutherland333** [comment] 2024-05-31 16:21
Our current hardware doesn't exhibit this problem (possibly due to higher quality sensors), so I'm going to close this issue.

**Closed** 2024-05-31 16:26 UTC
